// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SnowflakeItemMaster.Infrastructure;

#nullable disable

namespace SnowflakeItemMaster.Infrastructure.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20250515084538_UpdateTableLog")]
    partial class UpdateTableLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SnowflakeItemMaster.Domain.Entities.ItemMasterSourceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CommonModel")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("common_model");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Errors")
                        .HasColumnType("longtext")
                        .HasColumnName("errors");

                    b.Property<bool>("IsSentToSqs")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_sent_to_sqs");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sku");

                    b.Property<string>("SourceModel")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("source_model");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("validation_status");

                    b.HasKey("Id");

                    b.HasIndex("Sku");

                    b.ToTable("item_master_source_log");
                });
#pragma warning restore 612, 618
        }
    }
}
